[build]
  base = "garage-home"
  command = "npm run build"
  publish = "dist"

[[redirects]]
  from = "/shanty/*"
  to = "/shanty/index.html"
  status = 200

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200