[build]
  command = """
    cd garage-home && npm install && npm run build && \
    cd ../shanty-generator && npm install && npm run build && \
    mkdir -p ../garage-home/dist/shanty && \
    cp -r dist/* ../garage-home/dist/shanty/
  """
  publish = "garage-home/dist"

[[redirects]]
  from = "/shanty/*"
  to = "/shanty/index.html"
  status = 200

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200