[build]
  base = "garage-home"        # Tells Netlify which directory to work from
  command = "npm run build"   # Command to build the site
  publish = "dist"           # Directory containing the built site

[[redirects]]
  from = "/shanty/*"
  to = "/shanty/index.html"
  status = 200

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200