[build]
  command = """
    cd garage-home && npm install && npm run build
  """
  publish = "garage-home/dist"

[[redirects]]
  from = "/shanty/*"
  to = "/shanty/index.html"
  status = 200

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200