[build]
  base = "garage-home"
  command = """
    npm run build && \
    cd ../shanty-generator && npm install && npm run build && \
    mkdir -p ../garage-home/dist/shanty && \
    cp -r dist/* ../garage-home/dist/shanty/ && \
    cd ../text-synth && npm install && npm run build && \
    mkdir -p ../garage-home/dist/text-synth && \
    cp -r build/* ../garage-home/dist/text-synth/
  """
  publish = "dist"

[[redirects]]
  from = "/shanty/*"
  to = "/shanty/index.html"
  status = 200

[[redirects]]
  from = "/text-synth/*"
  to = "/text-synth/index.html"
  status = 200

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200